# Copyright 2006 The Android Open Source Project

LOCAL_CFLAGS += -DCONFIG_CTRL_IFACE_CLIENT_DIR=\"/data/misc/wifi/sockets\"
LOCAL_CFLAGS += -DCONFIG_CTRL_IFACE_CLIENT_PREFIX=\"wpa_ctrl_\"
# ++NANORADIO
ifeq ($(WIFI_USE_NANORADIO), true)

ifdef WIFI_DRIVER_SUPP_CONFIG_TEMPLATE
LOCAL_CFLAGS += -DWIFI_DRIVER_SUPP_CONFIG_TEMPLATE=\"$(WIFI_DRIVER_SUPP_CONFIG_TEMPLATE)\"
endif
ifdef WIFI_DRIVER_SUPP_CONFIG_FILE
LOCAL_CFLAGS += -DWIFI_DRIVER_SUPP_CONFIG_FILE=\"$(WIFI_DRIVER_SUPP_CONFIG_FILE)\"
endif
ifdef WIFI_DRIVER_SUPP_IFACE_DIR
LOCAL_CFLAGS += -DWIFI_DRIVER_SUPP_IFACE_DIR=\"$(WIFI_DRIVER_SUPP_IFACE_DIR)\"
endif
ifdef WIFI_DRIVER_STATUS_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_STATUS_PATH=\"$(WIFI_DRIVER_STATUS_PATH)\"
endif
ifdef WIFI_DRIVER_IFACE
LOCAL_CFLAGS += -DWIFI_DRIVER_IFACE=\"$(WIFI_DRIVER_IFACE)\"
endif
LOCAL_SRC_FILES += wifi/wifi_nano.c

else
# --NANORADIO

ifdef WIFI_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_PATH=\"$(WIFI_DRIVER_MODULE_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_NAME=\"$(WIFI_DRIVER_MODULE_NAME)\"
endif
ifdef WIFI_FIRMWARE_LOADER
LOCAL_CFLAGS += -DWIFI_FIRMWARE_LOADER=\"$(WIFI_FIRMWARE_LOADER)\"
endif
ifdef WIFI_DRIVER_FW_PATH_STA
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_STA=\"$(WIFI_DRIVER_FW_PATH_STA)\"
endif
ifdef WIFI_DRIVER_FW_PATH_AP
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_AP=\"$(WIFI_DRIVER_FW_PATH_AP)\"
endif
ifdef WIFI_DRIVER_FW_PATH_P2P
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_P2P=\"$(WIFI_DRIVER_FW_PATH_P2P)\"
endif
ifdef WIFI_DRIVER_FW_PATH_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_PARAM=\"$(WIFI_DRIVER_FW_PATH_PARAM)\"
endif

LOCAL_SRC_FILES += wifi/wifi.c

# ++NANORADIO
endif
# --NANORADIO

LOCAL_SHARED_LIBRARIES += libnetutils
